#!/usr/bin/env bash
# Generate a development .env with fresh random secrets. Never overwrites.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENVF="$HERE/.env"

if [ -f "$ENVF" ]; then
  echo "[make_env] $ENVF already exists — leaving it alone"
  exit 0
fi

rnd() { python3 -c "import secrets;print(secrets.token_hex($1))"; }

cat > "$ENVF" <<EOF
# GENERATED BY scripts/make_env.sh — development values. Do not commit.
SECRET_KEY=$(rnd 32)
POSTGRES_PASSWORD=$(rnd 16)
APP_DB_PASSWORD=$(rnd 16)

POSTGRES_DB=gautrack
POSTGRES_OWNER_USER=gautrack_owner
POSTGRES_APP_USER=gautrack_app
POSTGRES_HOST=127.0.0.1
POSTGRES_PORT=55432

SITE_ADDRESS=localhost
ACME_EMAIL=

# quoted: this path can contain spaces
PHOTO_DIR="$HERE/data/photos"
MAP_TILES_URL="https://tile.openstreetmap.org/{z}/{x}/{y}.png"
MAP_TILES_ATTRIBUTION="&copy; OpenStreetMap contributors"

SEED_DEMO=1
# dev serves plain HTTP on localhost, so the Secure cookie flag would break login
COOKIE_SECURE=0
TRUSTED_PROXY_COUNT=0
SESSION_IDLE_MINUTES_FIELD=720
SESSION_IDLE_MINUTES_ADMIN=120
LOG_LEVEL=info
EOF

chmod 600 "$ENVF"
mkdir -p "$HERE/data/photos"
echo "[make_env] wrote $ENVF (mode 600)"
