"""initial schema, audit/event hash chains, append-only guards, role grants

Revision ID: 0001_init
Revises:
Create Date: 2026-08-17

The DDL is written out longhand rather than autogenerated because the security
properties of this schema live in the triggers and the GRANTs, not in the
column list.
"""
from __future__ import annotations

from alembic import op

from config import settings

revision = "0001_init"
down_revision = None
branch_labels = None
depends_on = None

ZERO = "repeat('0',64)"

SCHEMA = """
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TYPE role_enum          AS ENUM ('super_admin','ulb_admin','field_officer','viewer','auditor');
CREATE TYPE keeper_type_enum   AS ENUM ('household','dairy_tabela','commercial','gaushala','trader','other');
CREATE TYPE species_enum       AS ENUM ('cattle','buffalo');
CREATE TYPE sex_enum           AS ENUM ('male','female','unknown');
CREATE TYPE age_class_enum     AS ENUM ('calf','young','adult','old');
CREATE TYPE tag_type_enum      AS ENUM ('pashu_aadhaar_12','rfid_lf','rfid_uhf','visual','microchip','none');
CREATE TYPE animal_status_enum AS ENUM ('registered','on_road_reported','impounded','in_gaushala',
                                        'released','transferred','deceased','tag_missing');
CREATE TYPE shelter_kind_enum  AS ENUM ('gaushala','nandishala','cattle_pound');
CREATE TYPE event_type_enum    AS ENUM ('registration','tagging','tag_lost','tag_replaced','sighting_road',
                                        'impound','release','fine_issued','fine_paid','gaushala_intake',
                                        'transfer_owner','death','correction','owner_merge','note');
CREATE TYPE fine_status_enum   AS ENUM ('issued','paid','waived','contested');

CREATE TABLE ulbs (
    id        SERIAL PRIMARY KEY,
    code      TEXT NOT NULL UNIQUE,
    name      TEXT NOT NULL,
    district  TEXT NOT NULL DEFAULT 'Rewari',
    lat       DOUBLE PRECISION,
    lng       DOUBLE PRECISION
);

CREATE TABLE users (
    id            UUID PRIMARY KEY,
    username      TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,           -- argon2id
    full_name     TEXT NOT NULL,
    role          role_enum NOT NULL,
    ulb_id        INTEGER REFERENCES ulbs(id),
    phone         TEXT,
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    totp_secret   TEXT,
    totp_enabled  BOOLEAN NOT NULL DEFAULT FALSE,
    failed_logins INTEGER NOT NULL DEFAULT 0,
    locked_until  TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX users_ulb_idx ON users(ulb_id);

-- id = sha256(cookie token). Storing the hash means a database dump does not
-- hand an attacker usable session cookies.
CREATE TABLE sessions (
    id         TEXT PRIMARY KEY,
    user_id    UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    csrf_token TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL,
    ip         TEXT,
    ua         TEXT,
    revoked_at TIMESTAMPTZ
);
CREATE INDEX sessions_user_idx ON sessions(user_id);
CREATE INDEX sessions_expiry_idx ON sessions(expires_at);

CREATE TABLE devices (
    id            UUID PRIMARY KEY,
    user_id       UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    label         TEXT,
    registered_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at  TIMESTAMPTZ,
    last_ip       TEXT
);

CREATE TABLE photos (
    id          UUID PRIMARY KEY,
    sha256      TEXT NOT NULL,
    mime        TEXT NOT NULL,
    bytes       INTEGER NOT NULL,
    path        TEXT NOT NULL,             -- relative to PHOTO_DIR; never user-controlled
    taken_at    TIMESTAMPTZ,
    lat         DOUBLE PRECISION,
    lng         DOUBLE PRECISION,
    uploaded_by UUID REFERENCES users(id),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX photos_sha_idx ON photos(sha256);

CREATE TABLE shelters (
    id            SERIAL PRIMARY KEY,
    ulb_id        INTEGER NOT NULL REFERENCES ulbs(id),
    name          TEXT NOT NULL,
    kind          shelter_kind_enum NOT NULL,
    capacity      INTEGER NOT NULL DEFAULT 0,
    current_count INTEGER NOT NULL DEFAULT 0,
    lat           DOUBLE PRECISION,
    lng           DOUBLE PRECISION,
    phone         TEXT
);

CREATE TABLE owners (
    id              UUID PRIMARY KEY,
    ulb_id          INTEGER NOT NULL REFERENCES ulbs(id),
    name            TEXT NOT NULL,
    relation_name   TEXT,
    phone_norm      TEXT,                  -- 10 digits, no country code
    phone_hash      TEXT,                  -- sha256(pepper||phone): dedupe without a plaintext index
    address         TEXT,
    ward_or_village TEXT,
    keeper_type     keeper_type_enum NOT NULL DEFAULT 'household',
    id_type         TEXT,                  -- NEVER an Aadhaar number: see SPEC §1.10
    id_last4        VARCHAR(4),
    lat             DOUBLE PRECISION,
    lng             DOUBLE PRECISION,
    gps_accuracy_m  DOUBLE PRECISION,
    photo_id        UUID REFERENCES photos(id),
    notes           TEXT,
    merged_into     UUID REFERENCES owners(id),
    created_by      UUID REFERENCES users(id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT owners_id_last4_digits CHECK (id_last4 IS NULL OR id_last4 ~ '^[0-9]{4}$')
);
CREATE INDEX owners_ulb_idx     ON owners(ulb_id);
CREATE INDEX owners_phone_idx   ON owners(phone_norm);
CREATE INDEX owners_created_idx ON owners(created_at);
CREATE INDEX owners_name_trgm   ON owners USING gin ((name || ' ' || coalesce(ward_or_village,'')) gin_trgm_ops);

CREATE TABLE animals (
    id                UUID PRIMARY KEY,
    ulb_id            INTEGER NOT NULL REFERENCES ulbs(id),
    owner_id          UUID REFERENCES owners(id),
    species           species_enum NOT NULL,
    sex               sex_enum NOT NULL DEFAULT 'unknown',
    age_class         age_class_enum NOT NULL DEFAULT 'adult',
    breed             TEXT,
    colour_markings   TEXT,
    tag_id            TEXT,
    tag_type          tag_type_enum NOT NULL DEFAULT 'none',
    secondary_tag_id  TEXT,
    status            animal_status_enum NOT NULL DEFAULT 'registered',
    current_shelter_id INTEGER REFERENCES shelters(id),
    photo_id          UUID REFERENCES photos(id),
    muzzle_photo_id   UUID REFERENCES photos(id),
    lat               DOUBLE PRECISION,
    lng               DOUBLE PRECISION,
    created_by        UUID REFERENCES users(id),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- one live tag = one animal, district-wide (SPEC §1.9)
CREATE UNIQUE INDEX animals_tag_uniq   ON animals(tag_id) WHERE tag_id IS NOT NULL;
CREATE INDEX animals_ulb_idx           ON animals(ulb_id);
CREATE INDEX animals_owner_idx         ON animals(owner_id);
CREATE INDEX animals_status_idx        ON animals(status);
CREATE INDEX animals_created_idx       ON animals(created_at);

CREATE TABLE events (
    id             UUID PRIMARY KEY,       -- client-generated (offline safe, idempotent)
    seq            BIGSERIAL NOT NULL UNIQUE,
    type           event_type_enum NOT NULL,
    animal_id      UUID REFERENCES animals(id),
    owner_id       UUID REFERENCES owners(id),
    ulb_id         INTEGER NOT NULL REFERENCES ulbs(id),
    user_id        UUID REFERENCES users(id),
    device_id      UUID,
    lat            DOUBLE PRECISION,
    lng            DOUBLE PRECISION,
    gps_accuracy_m DOUBLE PRECISION,
    occurred_at    TIMESTAMPTZ NOT NULL,
    received_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    payload        JSONB NOT NULL DEFAULT '{}'::jsonb,
    photo_ids      UUID[] NOT NULL DEFAULT '{}',
    prev_hash      TEXT NOT NULL DEFAULT '',
    hash           TEXT NOT NULL DEFAULT ''
);
CREATE INDEX events_animal_idx   ON events(animal_id);
CREATE INDEX events_owner_idx    ON events(owner_id);
CREATE INDEX events_ulb_idx      ON events(ulb_id);
CREATE INDEX events_type_idx     ON events(type);
CREATE INDEX events_occurred_idx ON events(occurred_at);

CREATE TABLE fines (
    id             UUID PRIMARY KEY,
    event_id       UUID REFERENCES events(id),
    animal_id      UUID REFERENCES animals(id),
    owner_id       UUID REFERENCES owners(id),
    ulb_id         INTEGER NOT NULL REFERENCES ulbs(id),
    offence_number INTEGER NOT NULL,
    amount         NUMERIC(12,2) NOT NULL,
    status         fine_status_enum NOT NULL DEFAULT 'issued',
    receipt_no     TEXT,
    issued_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    paid_at        TIMESTAMPTZ
);
CREATE INDEX fines_owner_idx ON fines(owner_id);
CREATE INDEX fines_ulb_idx   ON fines(ulb_id);

CREATE TABLE fine_schedule (
    offence_number  INTEGER PRIMARY KEY,
    amount          NUMERIC(12,2) NOT NULL,
    catching_charge NUMERIC(12,2) NOT NULL DEFAULT 0,
    fir_flag        BOOLEAN NOT NULL DEFAULT FALSE,
    note            TEXT
);

CREATE TABLE audit_log (
    id            BIGSERIAL PRIMARY KEY,
    ts            TIMESTAMPTZ NOT NULL,
    actor_user_id UUID,
    ip            TEXT,
    action        TEXT NOT NULL,
    table_name    TEXT NOT NULL,
    row_id        TEXT,
    before        JSONB,
    after         JSONB,
    prev_hash     TEXT NOT NULL,
    hash          TEXT NOT NULL
);
CREATE INDEX audit_log_table_row_idx ON audit_log(table_name, row_id);
CREATE INDEX audit_log_ts_idx        ON audit_log(ts);

CREATE TABLE login_attempts (
    id       BIGSERIAL PRIMARY KEY,
    ts       TIMESTAMPTZ NOT NULL DEFAULT now(),
    ip       TEXT NOT NULL,
    username TEXT,
    ok       BOOLEAN NOT NULL DEFAULT FALSE,
    kind     TEXT NOT NULL DEFAULT 'login'
);
CREATE INDEX login_attempts_ip_idx   ON login_attempts(kind, ip, ts DESC);
CREATE INDEX login_attempts_user_idx ON login_attempts(kind, username, ts DESC);
"""


# --------------------------------------------------------------------------- chains
CHAIN = f"""
-- Canonical serialisation of an audit row.  Defined ONCE and used by both the
-- writer (the trigger) and the reader (scripts/verify_chain.py), so the two can
-- never drift apart and produce a false BROKEN.
CREATE OR REPLACE FUNCTION gt_audit_payload(
        p_id bigint, p_ts timestamptz, p_actor uuid, p_ip text, p_action text,
        p_table text, p_row_id text, p_before jsonb, p_after jsonb)
RETURNS text LANGUAGE sql STABLE AS $fn$
  SELECT jsonb_build_object(
    'id',            p_id,
    'ts',            to_char(p_ts AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),
    'actor_user_id', p_actor,
    'ip',            p_ip,
    'action',        p_action,
    'table_name',    p_table,
    'row_id',        p_row_id,
    'before',        p_before,
    'after',         p_after)::text
$fn$;

-- SECURITY DEFINER: the application role has only SELECT on audit_log, so the
-- audit row is written with the schema owner's rights.  The app therefore
-- cannot forge, skip or delete its own audit trail.
CREATE OR REPLACE FUNCTION gt_audit() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $fn$
DECLARE
    v_before jsonb; v_after jsonb; v_prev text; v_hash text;
    v_actor uuid; v_ip text; v_row_id text; v_id bigint; v_ts timestamptz;
BEGIN
    -- A hash chain is only meaningful under a total order: serialise writers.
    PERFORM pg_advisory_xact_lock(7301);

    IF TG_OP = 'DELETE' THEN
        v_before := to_jsonb(OLD); v_after := NULL;         v_row_id := to_jsonb(OLD)->>'id';
    ELSIF TG_OP = 'UPDATE' THEN
        v_before := to_jsonb(OLD); v_after := to_jsonb(NEW); v_row_id := to_jsonb(NEW)->>'id';
    ELSE
        v_before := NULL;          v_after := to_jsonb(NEW); v_row_id := to_jsonb(NEW)->>'id';
    END IF;

    -- never copy credentials into the audit log
    IF TG_TABLE_NAME = 'users' THEN
        v_before := v_before - 'password_hash' - 'totp_secret';
        v_after  := v_after  - 'password_hash' - 'totp_secret';
    END IF;

    BEGIN
        v_actor := nullif(current_setting('app.user_id', true), '')::uuid;
    EXCEPTION WHEN others THEN
        v_actor := NULL;
    END;
    v_ip  := nullif(current_setting('app.ip', true), '');
    v_id  := nextval('audit_log_id_seq');
    v_ts  := clock_timestamp();

    SELECT hash INTO v_prev FROM audit_log ORDER BY id DESC LIMIT 1;
    v_prev := coalesce(v_prev, {ZERO});

    v_hash := encode(sha256(convert_to(
        v_prev || gt_audit_payload(v_id, v_ts, v_actor, v_ip, TG_OP,
                                   TG_TABLE_NAME, v_row_id, v_before, v_after),
        'UTF8')), 'hex');

    INSERT INTO audit_log(id, ts, actor_user_id, ip, action, table_name, row_id,
                          before, after, prev_hash, hash)
    VALUES (v_id, v_ts, v_actor, v_ip, TG_OP, TG_TABLE_NAME, v_row_id,
            v_before, v_after, v_prev, v_hash);
    RETURN NULL;
END $fn$;

CREATE TRIGGER owners_audit   AFTER INSERT OR UPDATE OR DELETE ON owners
    FOR EACH ROW EXECUTE FUNCTION gt_audit();
CREATE TRIGGER animals_audit  AFTER INSERT OR UPDATE OR DELETE ON animals
    FOR EACH ROW EXECUTE FUNCTION gt_audit();
CREATE TRIGGER users_audit    AFTER INSERT OR UPDATE OR DELETE ON users
    FOR EACH ROW EXECUTE FUNCTION gt_audit();
CREATE TRIGGER fines_audit    AFTER INSERT OR UPDATE OR DELETE ON fines
    FOR EACH ROW EXECUTE FUNCTION gt_audit();
CREATE TRIGGER shelters_audit AFTER INSERT OR UPDATE OR DELETE ON shelters
    FOR EACH ROW EXECUTE FUNCTION gt_audit();

-- ---- events: their own chain, plus append-only enforcement ---------------
CREATE OR REPLACE FUNCTION gt_event_payload(
        p_id uuid, p_seq bigint, p_type text, p_animal uuid, p_owner uuid,
        p_ulb integer, p_user uuid, p_device uuid, p_occurred timestamptz,
        p_payload jsonb, p_photo_ids uuid[])
RETURNS text LANGUAGE sql STABLE AS $fn$
  SELECT jsonb_build_object(
    'id',          p_id,
    'seq',         p_seq,
    'type',        p_type,
    'animal_id',   p_animal,
    'owner_id',    p_owner,
    'ulb_id',      p_ulb,
    'user_id',     p_user,
    'device_id',   p_device,
    'occurred_at', to_char(p_occurred AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),
    'payload',     p_payload,
    'photo_ids',   to_jsonb(p_photo_ids))::text
$fn$;

CREATE OR REPLACE FUNCTION gt_event_chain() RETURNS trigger
LANGUAGE plpgsql AS $fn$
DECLARE v_prev text;
BEGIN
    PERFORM pg_advisory_xact_lock(7302);
    SELECT hash INTO v_prev FROM events ORDER BY seq DESC LIMIT 1;
    NEW.prev_hash := coalesce(v_prev, {ZERO});
    NEW.hash := encode(sha256(convert_to(
        NEW.prev_hash || gt_event_payload(NEW.id, NEW.seq, NEW.type::text, NEW.animal_id,
            NEW.owner_id, NEW.ulb_id, NEW.user_id, NEW.device_id, NEW.occurred_at,
            NEW.payload, NEW.photo_ids),
        'UTF8')), 'hex');
    RETURN NEW;
END $fn$;
CREATE TRIGGER events_chain BEFORE INSERT ON events
    FOR EACH ROW EXECUTE FUNCTION gt_event_chain();

CREATE OR REPLACE FUNCTION gt_append_only() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
    RAISE EXCEPTION '% is append-only; % is not permitted', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'insufficient_privilege';
END $fn$;

-- statement-level so even a zero-row UPDATE is refused
CREATE TRIGGER events_append_only    BEFORE UPDATE OR DELETE ON events
    FOR EACH STATEMENT EXECUTE FUNCTION gt_append_only();
CREATE TRIGGER audit_log_append_only BEFORE UPDATE OR DELETE ON audit_log
    FOR EACH STATEMENT EXECUTE FUNCTION gt_append_only();
"""


def _grants(app_role: str) -> str:
    r = f'"{app_role}"'
    return f"""
-- ---- least privilege for the web process --------------------------------
GRANT USAGE ON SCHEMA public TO {r};

GRANT SELECT, INSERT, UPDATE, DELETE ON
      users, sessions, devices, photos, shelters, owners, animals, fines, login_attempts
      TO {r};

-- config tables: read-only for the app; changed by an operator via migrations
GRANT SELECT ON ulbs, fine_schedule TO {r};

-- events are append-only: no UPDATE/DELETE grant at all (SPEC §1.7)
GRANT SELECT, INSERT ON events TO {r};
REVOKE UPDATE, DELETE ON events FROM {r};

-- the audit log is readable but is written only by the SECURITY DEFINER trigger
GRANT SELECT ON audit_log TO {r};
REVOKE INSERT, UPDATE, DELETE ON audit_log FROM {r};

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO {r};
"""


SEED_REFERENCE = """
INSERT INTO ulbs (code, name, district, lat, lng) VALUES
  ('RWR','Rewari MC',   'Rewari', 28.1990, 76.6190),
  ('BWL','Bawal MC',    'Rewari', 28.0725, 76.5830),
  ('DHR','Dharuhera MC','Rewari', 28.2050, 76.7960),
  ('RUR','Rural/Other', 'Rewari', 28.2500, 76.5000);

-- PLACEHOLDER SCHEDULE — the DMC must confirm the statutory amounts before use.
-- Haryana practice referenced in SPEC §2: 1st offence Rs 5,100 release fee plus a
-- separate Rs 2,000 catching charge.
INSERT INTO fine_schedule (offence_number, amount, catching_charge, fir_flag, note) VALUES
  (1,  5100.00, 1880.00, FALSE, 'Haryana ULB practice: Rs 5,100 first release (Rewari/Ambala/Faridabad); catching charge = Rewari 2026 tender rate Rs 1,880/animal. Confirm order no. with ULB dept.'),
  (2, 11000.00, 1880.00, FALSE, 'Haryana ULB practice: Rs 11,000 repeat offence (Haryana govt press note). Confirm order no.'),
  (3, 11000.00, 1880.00, TRUE,  'Third+ offence: Rs 11,000 + FIR (BNS 291 negligent conduct w.r.t. animal) - Rewari admin announced FIRs 14 Aug 2026; not yet a notified schedule.');
"""


def upgrade() -> None:
    op.execute(SCHEMA)
    op.execute(CHAIN)
    op.execute(SEED_REFERENCE)
    op.execute(_grants(settings.postgres_app_user))


def downgrade() -> None:
    op.execute(
        """
        DROP TABLE IF EXISTS login_attempts, audit_log, fine_schedule, fines, events,
            animals, owners, shelters, photos, devices, sessions, users, ulbs CASCADE;
        DROP FUNCTION IF EXISTS gt_audit(), gt_audit_payload(bigint,timestamptz,uuid,text,text,text,text,jsonb,jsonb),
            gt_event_chain(), gt_append_only(),
            gt_event_payload(uuid,bigint,text,uuid,uuid,integer,uuid,uuid,timestamptz,jsonb,uuid[]) CASCADE;
        DROP TYPE IF EXISTS role_enum, keeper_type_enum, species_enum, sex_enum, age_class_enum,
            tag_type_enum, animal_status_enum, shelter_kind_enum, event_type_enum, fine_status_enum CASCADE;
        """
    )
